name: CI (build and tests)

on:
  push:
    branches: [ main, master ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm install --no-audit --no-fund

      - name: Build
        env:
          BASE_PATH: '/'
          VITE_DATA_BASE_PATH: '/data'
        run: npm run build

      - name: Run tests (if present)
        run: npm run -s test --if-present

